### ISSUE TITLE
UserCommand dont show the user properties when it's returning with errors

### ISSUE THREAD

**Issue by pangeaos** [grails-guides/command-objects-and-forms#6]
I have followed all the steps of this tutorial. I have a question?
When the userCommand have son errors, it will respond to edit view with the errors but I lost the values of user object (edit method)

```
def edit(User user) {
        respond user
    }

    def update(UserCommand userCommand) {
	    if (userCommand.hasErrors()) {
		    respond userCommand.errors, view: 'edit'
		    return
	    }
         ....
    }
```

![screen shot 2018-08-08 at 20 26 16](https://user-images.githubusercontent.com/221474/43875106-8d0f68a6-9b4c-11e8-800c-ffe9c3e30f51.png)
![screen shot 2018-08-08 at 20 28 04](https://user-images.githubusercontent.com/221474/43875107-8d27e728-9b4c-11e8-9124-4af92ec38c3a.png)

**Comment by pangeaos** [comment]
I let the Game field empty.

![screen shot 2018-08-08 at 21 23 18](https://user-images.githubusercontent.com/221474/43876241-6278b9da-9b51-11e8-8e48-4a6bee5d13f2.png)

**Comment by niravassar** [comment]
That is because in the `respond` it is only sending the errors back and not the contents  of the command. You can use the respond to send back the model as well, just pass it in as an argument.

See the doc:
https://docs.grails.org/latest/ref/Controllers/respond.html
